order/build.gradle
order/src/main/java/com/faster/order/app/global/exception/OrderErrorCode.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
order/src/main/resources/properties/base.yml

[order] 주문 삭제 기능 구현

---

message/build.gradle
message/src/main/java/com/faster/message/app/global/MessageInvalidBySendAtException.java
message/src/main/java/com/faster/message/app/global/MessageInvalidBySlackIdException.java
message/src/main/java/com/faster/message/app/global/enums/MessageErrorCode.java
message/src/main/java/com/faster/message/app/global/handler/MessageExceptionHandler.java
message/src/main/java/com/faster/message/app/global/response/MessageResponseCode.java
message/src/main/java/com/faster/message/app/message/application/dto/CreateMessageRequestDto.java
message/src/main/java/com/faster/message/app/message/application/usecase/MessageService.java
message/src/main/java/com/faster/message/app/message/application/usecase/MessageUseCase.java
message/src/main/java/com/faster/message/app/message/domain/entity/Message.java
message/src/main/java/com/faster/message/app/message/domain/enums/Type.java
message/src/main/java/com/faster/message/app/message/domain/repository/MessageRepository.java
message/src/main/java/com/faster/message/app/message/presentation/dto/response/CreateMessageResponseDto.java
message/src/main/java/com/faster/message/app/message/presentation/internal/MessageInternalController.java

- 이슈 번호: #30 
- **as-is**
- (변경 전 설명을 여기에 작성)
적절하게 메시지를 던질 수 있도록 예외처리 핸들러를 구현했다.
메시지 생성에서 슬랙 아이디, 타입, 생성자 확인이 필요한데, 좀 더 개발을 진행하면서 회원 부분의 서비스부터 개발하면서 슬랙 아이디 API 조회가 구현될 때 추가할 예정입니다.

[message] DDD 계층 구조에 따라서 도메인 설계하기

---

hub/src/main/java/com/faster/hub/app/global/exception/HubErrorCode.java
hub/src/main/java/com/faster/hub/app/hub/application/dto/GetHubApplicationResponseDto.java
hub/src/main/java/com/faster/hub/app/hub/application/dto/GetHubResponseApplicationResponseDto.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
hub/src/main/java/com/faster/hub/app/hub/domain/repository/HubRepository.java
hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
hub/src/main/java/com/faster/hub/app/hub/presentation/dto/GetHubResponseDto.java
hub/src/test/hub.http

[hub] 단건 조회

---

hub/src/main/java/com/faster/hub/app/hub/application/dto/UpdateHubApplicationRequestDto.java
hub/src/main/java/com/faster/hub/app/hub/application/dto/UpdateHubApplicationResponseDto.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
hub/src/main/java/com/faster/hub/app/hub/domain/entity/Hub.java
hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
hub/src/main/java/com/faster/hub/app/hub/presentation/dto/UpdateHubRequestDto.java
hub/src/main/java/com/faster/hub/app/hub/presentation/dto/UpdateHubResponseDto.java
hub/src/test/hub.http

- 이슈 번호: #37
- 현재는 단순 내용 업데이트 입니다.
- 후에 허브 경로와 함께 수정하도록 변경 예정입니다.

[hub] 단건 수정

---

common/build.gradle
common/src/main/java/com/common/exception/GlobalErrorHandler.java

[common] 공통 코드 의존성, 글로벌익셉션 핸들러 추가

---

common/src/main/java/com/common/response/PageResponse.java

[common] 페이지응답 레코드에 map() 메소드 추가

---

hub/src/main/java/com/faster/hub/app/hub/application/dto/SaveHubApplicationRequestDto.java
hub/src/main/java/com/faster/hub/app/hub/application/dto/SaveHubApplicationResponseDto.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
hub/src/main/java/com/faster/hub/app/hub/presentation/dto/SaveHubRequestDto.java
hub/src/main/java/com/faster/hub/app/hub/presentation/dto/SaveHubResponseDto.java
hub/src/main/java/com/faster/hub/app/hub/presentation/dto/UpdateHubRequestDto.java

- 이슈 번호: #35
- **as-is**
- create여서 컨벤션에 맞지않음
- cud 작업에서 권한 체크가 필요

[hub] api refactor - 클래스명 변경, 권한 변경

---

common/src/main/java/com/common/domain/BaseEntity.java
delivery/build.gradle
delivery/src/main/java/com/faster/delivery/DeliveryApplication.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/application/dto/DeliverySaveDto.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/application/usecase/DeliveryService.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/application/usecase/DeliveryServiceImpl.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/domain/entity/Delivery.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/domain/entity/DeliveryRoute.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/domain/repository/DeliveryRepository.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/feign/CompanyClient.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/feign/HubClient.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/feign/dto/company/CompanyGetResponseDto.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/feign/dto/hub/HubPathRequestDto.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/feign/dto/hub/HubPathResponseDto.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/jpa/DeliveryJpaRepository.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/jpa/DeliveryRepositoryCustom.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/jpa/DeliveryRepositoryCustomImpl.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/presentaion/DeliveryApiController.java
delivery/src/main/java/com/faster/delivery/app/domains/delivery/presentaion/dto/DeliverySaveRequestDto.java
delivery/src/main/resources/application-develop.yml
delivery/src/main/resources/application-test.yml
delivery/src/main/resources/application.yml
delivery/src/test/java/com/faster/delivery/DeliveryApplicationTests.java
delivery/src/test/java/com/faster/delivery/app/domains/delivery/application/usecase/DeliveryServiceImplTest.java
delivery/src/test/java/com/faster/delivery/app/domains/delivery/application/usecase/DeliveryServiceTest.java

- 이슈 번호: #39
- **as-is**
- 
- 추후 변경 예정 항목 
```
- 서킷브레이커에 의한 예외처리 적용 
- 배달경로 <-> 배달 기사 배정 기능 추가 
```

[delivery] 배달 생성 기능 추가

---

order/build.gradle
order/src/main/java/com/faster/order/app/global/config/QuerydslConfig.java
order/src/main/java/com/faster/order/app/global/exception/OrderErrorCode.java
order/src/main/java/com/faster/order/app/global/utils/QuerydslUtil.java
order/src/main/java/com/faster/order/app/order/application/dto/request/SearchOrderConditionDto.java
order/src/main/java/com/faster/order/app/order/application/dto/response/SearchOrderApplicationResponseDto.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
order/src/main/java/com/faster/order/app/order/domain/entity/OrderItem.java
order/src/main/java/com/faster/order/app/order/domain/repository/OrderRepository.java
order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepository.java
order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepositoryCustom.java
order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepositoryCustomImpl.java
order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/dto/response/OrderQuerydslResponseDto.java
order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
order/src/main/java/com/faster/order/app/order/presentation/dto/response/SearchOrderResponseDto.java
order/src/main/resources/properties/base.yml
order/src/main/resources/properties/cloud.yml
order/src/main/resources/properties/datasource.yml
order/src/main/resources/properties/jpa.yml
order/src/test/java/com/faster/order/app/order/application/usecase/OrderServiceTest.java
order/src/test/java/com/faster/order/app/order/fixture/OrderFixture.java
order/src/test/java/com/faster/order/app/order/utils/DatabaseCleanUp.java
order/src/test/order.http

[order] 주문 검색 조회

---

order/src/main/java/com/faster/order/app/order/application/dto/response/GetOrderDetailApplicationResponseDto.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
order/src/main/java/com/faster/order/app/order/presentation/dto/response/GetOrderDetailResponseDto.java

[order] 단건 조회, 삭제 refactor

---

order/src/main/java/com/faster/order/app/global/exception/OrderErrorCode.java
order/src/main/java/com/faster/order/app/order/application/dto/response/CancelOrderApplicationResponseDto.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
order/src/main/java/com/faster/order/app/order/domain/repository/OrderRepository.java
order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
order/src/main/java/com/faster/order/app/order/presentation/dto/response/CancelOrderResponseDto.java
order/src/test/order.http

[order] 주문 취소 기능 구현

---

order/src/main/java/com/faster/order/app/order/application/dto/response/InternalConfirmOrderApplicationResponseDto.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
order/src/main/java/com/faster/order/app/order/presentation/OrderInternalController.java
order/src/main/java/com/faster/order/app/order/presentation/dto/response/InternalConfirmOrderResponseDto.java
order/src/test/order.http

[order] 내부 주문 확정 기능 구현

---

message/src/main/java/com/faster/message/app/message/application/dto/SaveGeminiMessageRequestDto.java
message/src/main/java/com/faster/message/app/message/application/dto/SaveMessageRequestDto.java
message/src/main/java/com/faster/message/app/message/application/usecase/MessageService.java
message/src/main/java/com/faster/message/app/message/application/usecase/MessageServiceImpl.java
message/src/main/java/com/faster/message/app/message/presentation/dto/response/SaveMessageResponseDto.java
message/src/main/java/com/faster/message/app/message/presentation/internal/MessageInternalController.java

코드 컨벤션 규칙에 따라 create -> save 으로 수정한다.
지미니 Body 안에 내용 형식을 메서드로 분리하는 요청에 따라 분리했다.!
- 이슈 번호: #30
- **as-is**
- create -> save
- 요청 형식 분할하기!
```
private Map<String, Object> getStringObjectMap(String prompt) {
return Map.of(
"contents", new Object[]{
Map.of("parts", new Object[]{
Map.of("text", prompt)
})
}
);
```

[message] 코드 컨벤션 규칙에 따라 수정 및 코드 분할

---

order/src/main/java/com/faster/order/app/order/application/dto/request/SaveOrderApplicationRequestDto.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
order/src/main/java/com/faster/order/app/order/domain/entity/OrderItem.java
order/src/main/java/com/faster/order/app/order/domain/entity/OrderItems.java
order/src/main/java/com/faster/order/app/order/domain/entity/OrdererInfo.java
order/src/main/java/com/faster/order/app/order/domain/repository/OrderRepository.java
order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
order/src/main/java/com/faster/order/app/order/presentation/dto/request/SaveOrderRequestDto.java
order/src/test/java/com/faster/order/app/order/fixture/OrderFixture.java
order/src/test/order.http

[order] 주문 생성 기능 구현

---

product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
product/src/main/java/com/faster/product/app/product/application/dto/GetProductDetailApplicationResponseDto.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepository.java
product/src/main/java/com/faster/product/app/product/presentation/dto/ProductController.java
product/src/main/java/com/faster/product/app/product/presentation/dto/ProductInternalController.java
product/src/main/java/com/faster/product/app/product/presentation/dto/response/GetProductDetailResponseDto.java
product/src/main/resources/db/data.sql
product/src/main/resources/properties/datasource.yml
product/src/test/product.http

[product] 상품 단건 조회 구현

---

product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/presentation/dto/ProductController.java
product/src/test/product.http

[product] 상품 단건 삭제 구현

---

product/src/main/java/com/faster/product/app/product/application/dto/request/UpdateProductApplicationRequestDto.java
product/src/main/java/com/faster/product/app/product/application/dto/response/GetProductDetailApplicationResponseDto.java
product/src/main/java/com/faster/product/app/product/application/dto/response/UpdateProductApplicationResponseDto.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
product/src/main/java/com/faster/product/app/product/presentation/ProductController.java
product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
product/src/main/java/com/faster/product/app/product/presentation/dto/request/UpdateProductRequestDto.java
product/src/main/java/com/faster/product/app/product/presentation/dto/response/GetProductDetailResponseDto.java
product/src/main/java/com/faster/product/app/product/presentation/dto/response/UpdateProductResponseDto.java
product/src/test/product.http

[product] 상품 수정 기능 구현

---

product/src/main/java/com/faster/product/app/product/application/dto/response/GetProductDetailApplicationResponseDto.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/presentation/dto/response/GetProductDetailResponseDto.java

[product] 상품 조회/삭제 리팩토링

---

product/src/main/java/com/faster/product/app/product/application/dto/request/SaveProductApplicationRequestDto.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
product/src/main/java/com/faster/product/app/product/presentation/ProductController.java
product/src/main/java/com/faster/product/app/product/presentation/dto/request/SaveProductRequestDto.java
product/src/test/product.http

[product] 상품 생성 기능 구현

---

product/src/main/java/com/faster/product/app/product/application/usecase/GetProductsApplicationResponseDto.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
product/src/main/java/com/faster/product/app/product/presentation/dto/response/GetProductsResponseDto.java
product/src/test/product.http

[product] 내부 상품 목록 조회

---

user/src/main/resources/application.yml
user/src/main/resources/properties/base.yml
user/src/main/resources/properties/cloud.yml
user/src/main/resources/properties/datasource.yml
user/src/main/resources/properties/jpa.yml
user/src/main/resources/properties/jwt.yml

- 이슈 번호: #99 
- **as-is**
- application.yml 파일이 한 파일로 관리
- **to-be**

[user] 설정파일 변경

---

product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
product/src/main/java/com/faster/product/app/product/application/dto/request/UpdateStocksApplicationRequestDto.java
product/src/main/java/com/faster/product/app/product/application/dto/response/UpdateStocksApplicationResponseDto.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
product/src/main/java/com/faster/product/app/product/presentation/dto/request/UpdateStocksRequestDto.java
product/src/main/java/com/faster/product/app/product/presentation/dto/response/UpdateStocksResponseDto.java
product/src/test/product.http

[product] 내부 상품 재고 수정 기능 구현

---

product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
product/src/main/java/com/faster/product/app/product/application/CompanyClient.java
product/src/main/java/com/faster/product/app/product/application/dto/request/UpdateStocksApplicationRequestDto.java
product/src/main/java/com/faster/product/app/product/application/dto/response/GetCompanyApplicationResponseDto.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
product/src/main/java/com/faster/product/app/product/infrastructure/CompanyClientImpl.java
product/src/main/java/com/faster/product/app/product/infrastructure/feign/CompanyFeignClient.java
product/src/main/java/com/faster/product/app/product/infrastructure/feign/dto/response/GetCompanyResponseDto.java
product/src/main/java/com/faster/product/app/product/presentation/ProductController.java

- 이슈 번호: #119 
- **as-is**
- 업체 서비스 구현 전이라 테스트 미수행 상태입니다.

[product] 업체 서비스 클라이언트 연동

---

delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliveryUpdateDto.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryService.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/Delivery.java
delivery/src/main/java/com/faster/delivery/app/delivery/domain/repository/DeliveryRepository.java
delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java
delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/DeliveryUpdateRequestDto.java

- 이슈 번호: #120
- 권한 체크 로직 추후 구현 예정

[delivery] feat: 배송 상태 업데이트 기능 구현

---

delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/hub/HubPathResponseDto.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/DeliveryManagerDetailDto.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/DeliveryManagerUpdateDto.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerService.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/entity/DeliveryManager.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/repository/DeliveryManagerRepository.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/DeliveryManagerApiController.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/DeliveryManagerGetDetailResponseDto.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/DeliveryManagerUpdateRequestDto.java

- BaseEntity createdBy 메서드 삭제
- 이슈 번호: #128
- 다른 서비스 요청 로직 추후 구현 
- 권한 검사 로직 추후 구현

[deliveryManager] feat: 배송담당자 상세조회,수정,삭제 기능 추가

---

delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryService.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
delivery/src/main/java/com/faster/delivery/app/delivery/domain/repository/DeliveryRepository.java
delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java

- 이슈 번호: #127 
- 권한 검증 로직 추후 구현 예정

[delivery] feat: 배송 삭제 기능 구현 

---

product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
product/src/main/java/com/faster/product/app/product/application/dto/request/GetProductsApplicationResponseDto.java
product/src/main/java/com/faster/product/app/product/application/dto/request/SearchProductConditionDto.java
product/src/main/java/com/faster/product/app/product/application/dto/response/SearchProductApplicationResponseDto.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/domain/criteria/SearchProductCriteria.java
product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepositoryCustom.java
product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepositoryCustomImpl.java
product/src/main/java/com/faster/product/app/product/presentation/ProductController.java
product/src/main/java/com/faster/product/app/product/presentation/dto/response/GetProductsResponseDto.java
product/src/main/java/com/faster/product/app/product/presentation/dto/response/SearchProductResponseDto.java
product/src/test/product.http

[product] 상품 목록 검색 기능 구현

---

hub/src/main/java/com/faster/hub/app/hub/application/dto/response/GetHubsApplicationResponseDto.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
hub/src/main/java/com/faster/hub/app/hub/domain/entity/Hub.java
hub/src/main/java/com/faster/hub/app/hub/domain/repository/HubRepository.java
hub/src/main/java/com/faster/hub/app/hub/presentation/GetHubsResponseDto.java
hub/src/main/java/com/faster/hub/app/hub/presentation/HubInternalController.java
hub/src/test/hub.http

- 이슈 번호: #125
- **to-be**
- api 명세서 업데이트 했습니다.

[hub] 허브 담당자 컬럼 추가 및 리스트 내부 조회

---

delivery/build.gradle
delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/CompanyDto.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryService.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/Delivery.java
delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/CompanyFeignClient.java
delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/DeliveryManagerFeignClient.java
delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/HubFeginClient.java
delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/company/CompanyGetResponseDto.java
delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java
delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryInternalController.java
delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/api/DeliverySaveRequestDto.java
delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/api/DeliveryUpdateRequestDto.java
delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/internal/DeliverySaveInternalRequestDto.java
delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/internal/DeliveryUpdateInternalRequestDto.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/HubFeginClient.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/UserFeginClient.java
delivery/src/main/java/com/faster/delivery/app/global/config/FeignClientConfig.java

- 이슈 번호: #137 
- 예외처리 로직 추가 예정 
- order 측 업데이트 로직 추가 예정 
- 권한 검증 로직 추가 예정

[delivery] feat: internal api 기본 구성 추가

---

order/src/main/java/com/faster/order/app/order/application/client/CompanyClient.java
order/src/main/java/com/faster/order/app/order/application/client/DeliveryClient.java
order/src/main/java/com/faster/order/app/order/application/client/ProductClient.java
order/src/main/java/com/faster/order/app/order/application/dto/request/SaveDeliveryApplicationRequestDto.java
order/src/main/java/com/faster/order/app/order/application/dto/response/CancelDeliveryApplicationResponseDto.java
order/src/main/java/com/faster/order/app/order/application/dto/response/SaveDeliveryApplicationResponseDto.java
order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
order/src/main/java/com/faster/order/app/order/domain/repository/OrderRepository.java
order/src/main/java/com/faster/order/app/order/infrastructure/CompanyClientImpl.java
order/src/main/java/com/faster/order/app/order/infrastructure/DeliveryClientImpl.java
order/src/main/java/com/faster/order/app/order/infrastructure/ProductClientImpl.java
order/src/main/java/com/faster/order/app/order/infrastructure/feign/DeliveryFeignClient.java
order/src/main/java/com/faster/order/app/order/infrastructure/feign/dto/request/CancelDeliveryRequestDto.java
order/src/main/java/com/faster/order/app/order/infrastructure/feign/dto/request/SaveDeliveryRequestDto.java
order/src/main/java/com/faster/order/app/order/infrastructure/feign/dto/response/CancelDeliveryResponseDto.java
order/src/main/java/com/faster/order/app/order/infrastructure/feign/dto/response/SaveDeliveryResponseDto.java
order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepository.java
order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepositoryCustomImpl.java
order/src/main/resources/db/data.sql

- 이슈 번호: #122
- **as-is**
- 배송 클라이언트 연동 테스트 전입니다.

[order] 배송 서비스 클라이언트 연동

---

common/src/main/java/com/common/exception/CustomException.java
common/src/main/java/com/common/exception/GlobalErrorHandler.java
gateway/src/main/java/com/faster/gateway/app/global/security/handler/ExceptionHandlingFilter.java
order/src/main/java/com/faster/order/app/global/feign/FeignClientErrorDecoder.java

- 이슈 번호: #141 
- **as-is**
- feignClientErrorDecoder 를 활용하여, 보다 명시적인 예외 처리를 수행할 수 있습니다.
- feign에서 제공하는 exception을 처리하는 불편함 해소 가능

[common] feignClient 에러디코더 추가에 따른 공통 예외 수정

---

company/src/main/java/com/faster/company/app/company/application/dto/response/GetCompanyApplicationResponseDto.java
company/src/main/java/com/faster/company/app/company/application/usecase/CompanyService.java
company/src/main/java/com/faster/company/app/company/application/usecase/CompanyServiceImpl.java
company/src/main/java/com/faster/company/app/company/presentation/CompanyController.java
company/src/main/java/com/faster/company/app/company/presentation/dto/response/GetCompanyResponseDto.java
company/src/test/company.http

[company] 업체 단건 조회 기능 구현

---

hub/build.gradle
hub/src/main/java/com/faster/hub/app/global/config/QuerydslConfig.java
hub/src/main/java/com/faster/hub/app/global/exception/HubErrorCode.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/request/GetHubsApplicationRequestDto.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/request/SearchHubCondition.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/response/GetHubsApplicationInternalResponseDto.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/response/GetHubsApplicationResponseDto.java
hub/src/main/java/com/faster/hub/app/hub/domain/projection/SearchHubProjection.java
hub/src/main/java/com/faster/hub/app/hub/domain/repository/HubRepository.java
hub/src/main/java/com/faster/hub/app/hub/infrastructure/persistence/HubJpaRepository.java
hub/src/main/java/com/faster/hub/app/hub/infrastructure/persistence/HubJpaRepositoryCustom.java
hub/src/main/java/com/faster/hub/app/hub/infrastructure/persistence/HubJpaRepositoryCustomImpl.java
hub/src/main/java/com/faster/hub/app/hub/infrastructure/persistence/command/SearchHubsByConditionCommand.java
hub/src/main/java/com/faster/hub/app/hub/infrastructure/persistence/util/QuerydslUtil.java
hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
hub/src/main/java/com/faster/hub/app/hub/presentation/HubInternalController.java
hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/GetHubsInternalResponseDto.java
hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/GetHubsResponseDto.java
hub/src/test/hub.http

[hub] search

---

company/src/main/java/com/faster/company/app/company/application/client/ProductClient.java
company/src/main/java/com/faster/company/app/company/application/dto/request/UpdateCompanyApplicationRequestDto.java
company/src/main/java/com/faster/company/app/company/application/dto/request/UpdateProductHubApplicationRequestDto.java
company/src/main/java/com/faster/company/app/company/application/dto/response/UpdateCompanyApplicationResponseDto.java
company/src/main/java/com/faster/company/app/company/application/dto/response/UpdateProductHubApplicationResponseDto.java
company/src/main/java/com/faster/company/app/company/application/usecase/CompanyService.java
company/src/main/java/com/faster/company/app/company/application/usecase/CompanyServiceImpl.java
company/src/main/java/com/faster/company/app/company/domain/command/UpdateCompanyCommand.java
company/src/main/java/com/faster/company/app/company/domain/entity/Company.java
company/src/main/java/com/faster/company/app/company/infrastructure/HubClientImpl.java
company/src/main/java/com/faster/company/app/company/infrastructure/ProductClientImpl.java
company/src/main/java/com/faster/company/app/company/infrastructure/feign/ProductFeignClient.java
company/src/main/java/com/faster/company/app/company/infrastructure/feign/dto/request/UpdateProductHubRequestDto.java
company/src/main/java/com/faster/company/app/company/infrastructure/feign/dto/response/UpdateProductHubResponseDto.java
company/src/main/java/com/faster/company/app/company/presentation/CompanyController.java
company/src/main/java/com/faster/company/app/company/presentation/dto/request/UpdateCompanyRequestDto.java
company/src/main/java/com/faster/company/app/company/presentation/dto/response/UpdateCompanyResponseDto.java
company/src/main/java/com/faster/company/app/global/exception/CompanyErrorCode.java
company/src/test/company.http

- 이슈 번호: #154 
- **as-is**
- 상품 내부 api 구현 전이라 테스트 진행 전입니다.

[company] 업체 수정 기능 구현

---

company/src/main/java/com/faster/company/app/company/application/client/ProductClient.java
company/src/main/java/com/faster/company/app/company/application/usecase/CompanyService.java
company/src/main/java/com/faster/company/app/company/application/usecase/CompanyServiceImpl.java
company/src/main/java/com/faster/company/app/company/domain/entity/Company.java
company/src/main/java/com/faster/company/app/company/infrastructure/ProductClientImpl.java
company/src/main/java/com/faster/company/app/company/infrastructure/feign/ProductFeignClient.java
company/src/main/java/com/faster/company/app/company/presentation/CompanyController.java
company/src/main/java/com/faster/company/app/company/presentation/dto/response/UpdateCompanyResponseDto.java
company/src/test/company.http

- 이슈 번호: #159
- **as-is**
- 상품 내부 api 구현 전이라 테스트 수행 전입니다.

[company] 업체 단건 삭제 기능 구현

---

product/src/main/java/com/faster/product/app/product/application/dto/request/UpdateProductHubApplicationRequestDto.java
product/src/main/java/com/faster/product/app/product/application/dto/response/UpdateProductHubApplicationResponseDto.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepository.java
product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
product/src/main/java/com/faster/product/app/product/presentation/dto/request/UpdateProductHubRequestDto.java
product/src/main/java/com/faster/product/app/product/presentation/dto/response/UpdateProductHubResponseDto.java
product/src/test/java/com/faster/product/app/product/application/usecase/ProductServiceTest.java
product/src/test/product.http

[product] 상품 허브 업데이트 내부 api 구현

---

product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepository.java
product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
product/src/test/java/com/faster/product/app/product/application/usecase/ProductServiceTest.java
product/src/test/product.http

[product] 업체별 상품 삭제 내부 api 구현

---

order/src/main/java/com/faster/order/app/order/domain/criteria/SearchOrderCriteria.java
order/src/main/java/com/faster/order/app/order/domain/enums/OrderStatus.java
order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepositoryCustomImpl.java
order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
order/src/main/java/com/faster/order/app/order/presentation/dto/request/InternalUpdateOrderStatusRequestDto.java

[order] 주문 서비스 명세에 따른 이넘값 수정 외

---

company/src/main/java/com/faster/company/app/company/application/dto/request/GetCompaniesApplicationRequestDto.java
company/src/main/java/com/faster/company/app/company/application/dto/request/SearchCompaniesCondition.java
company/src/main/java/com/faster/company/app/company/application/dto/response/GetCompaniesApplicationResponseDto.java
company/src/main/java/com/faster/company/app/company/application/usecase/CompanyService.java
company/src/main/java/com/faster/company/app/company/application/usecase/CompanyServiceImpl.java
company/src/main/java/com/faster/company/app/company/domain/projection/SearchCompaniesProjection.java
company/src/main/java/com/faster/company/app/company/domain/repository/CompanyRepository.java
company/src/main/java/com/faster/company/app/company/infrastructure/feign/ProductFeignClient.java
company/src/main/java/com/faster/company/app/company/infrastructure/persistence/command/SearchCompaniesByConditionCommand.java
company/src/main/java/com/faster/company/app/company/infrastructure/persistence/jpa/CompanyJpaRepository.java
company/src/main/java/com/faster/company/app/company/infrastructure/persistence/jpa/CompanyJpaRepositoryCustom.java
company/src/main/java/com/faster/company/app/company/infrastructure/persistence/jpa/CompanyJpaRepositoryCustomImpl.java
company/src/main/java/com/faster/company/app/company/infrastructure/persistence/util/QuerydslUtil.java
company/src/main/java/com/faster/company/app/company/presentation/CompanyController.java
company/src/main/java/com/faster/company/app/company/presentation/dto/response/GetCompaniesResponseDto.java
company/src/main/java/com/faster/company/app/global/config/QuerydslConfig.java
company/src/main/java/com/faster/company/app/global/exception/CompanyErrorCode.java
company/src/test/company.http

[company] search

---

hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
hub/src/main/java/com/faster/hub/app/hub/domain/repository/HubRepository.java
hub/src/main/java/com/faster/hub/app/hub/presentation/HubInternalController.java
hub/src/test/hub.http

- 이슈 번호: #176
- **to-be**
- 추후 동적쿼리로 개선이 필요합니다.

[hub] 허브담당자의 허브 조회

---

product/src/main/java/com/faster/product/app/global/config/FeignClientConfig.java
product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
product/src/main/java/com/faster/product/app/global/feign/FeignClientErrorDecoder.java
product/src/main/java/com/faster/product/app/product/application/dto/response/GetCompanyApplicationResponseDto.java
product/src/main/java/com/faster/product/app/product/domain/criteria/SearchProductCriteria.java
product/src/main/java/com/faster/product/app/product/infrastructure/feign/dto/response/GetCompanyResponseDto.java
product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepositoryCustomImpl.java
product/src/main/java/com/faster/product/app/product/presentation/ProductController.java
product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
product/src/test/product.http

[product] 상품 리팩토링

---

delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/DeliveryRoute.java

[delivery] 배송 경로 배송담장자 유저 id 컬럼 추가

---

order/build.gradle
order/src/main/java/com/faster/order/app/global/config/FeignClientConfig.java
order/src/main/java/com/faster/order/app/global/filter/LoggingFilter.java
order/src/main/java/com/faster/order/app/order/application/dto/request/UpdateStocksApplicationRequestDto.java
order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
order/src/main/java/com/faster/order/app/order/domain/entity/OrderItem.java
order/src/main/java/com/faster/order/app/order/domain/entity/OrderItems.java
order/src/main/java/com/faster/order/app/order/domain/entity/OrdererInfo.java
order/src/main/resources/application.yml
order/src/main/resources/logback-spring.xml
order/src/main/resources/logback/error-file-appender.xml
order/src/main/resources/logback/info-file-appender.xml
order/src/main/resources/properties/zipkin.yml

[order] 주문 리팩토링

---

company/build.gradle
company/src/main/java/com/faster/company/app/company/application/usecase/CompanyServiceImpl.java
company/src/main/java/com/faster/company/app/company/infrastructure/feign/ProductFeignClient.java
company/src/main/java/com/faster/company/app/company/presentation/CompanyInternalController.java
company/src/main/java/com/faster/company/app/global/config/FeignClientConfig.java
company/src/main/java/com/faster/company/app/global/feign/FeignClientErrorDecoder.java
company/src/main/java/com/faster/company/app/global/filter/LoggingFilter.java
company/src/main/resources/application.yml
company/src/main/resources/db/data.sql
company/src/main/resources/logback-spring.xml
company/src/main/resources/logback/error-file-appender.xml
company/src/main/resources/logback/info-file-appender.xml
company/src/main/resources/properties/zipkin.yml
company/src/test/company.http

[company] 업체 리팩토링

---

delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliveryRouteUpdateDto.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/HubRouteDto.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryService.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/Delivery.java
delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/DeliveryRoute.java
delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java
delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/api/DeliveryRouteUpdateRequestDto.java

- 이슈 번호: #195 
- 배송의 status 도 추후 정리 예정

[#195][delivery] feat: 배송경로 업데이트 기능 추가

---

hub/build.gradle
hub/src/main/java/com/faster/hub/app/global/config/RedisCacheConfig.java
hub/src/main/java/com/faster/hub/app/global/config/RedisConfig.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
hub/src/main/resources/application.yml
hub/src/main/resources/properties/redis.yml

[hub] route 캐싱 작업

---

message/build.gradle
message/src/main/java/com/faster/message/app/global/QueryDslConfig/QueryDslConfig.java
message/src/main/java/com/faster/message/app/global/response/MessageResponseCode.java
message/src/main/java/com/faster/message/app/message/application/usecase/MessageService.java
message/src/main/java/com/faster/message/app/message/application/usecase/MessageServiceImpl.java
message/src/main/java/com/faster/message/app/message/domain/entity/Message.java
message/src/main/java/com/faster/message/app/message/domain/repository/MessageRepository.java
message/src/main/java/com/faster/message/app/message/infrastructure/persistence/jpa/MessageJpaRepository.java
message/src/main/java/com/faster/message/app/message/infrastructure/persistence/jpa/MessageJpaRepositoryImpl.java
message/src/main/java/com/faster/message/app/message/infrastructure/persistence/jpa/MessageRepositoryCustom.java
message/src/main/java/com/faster/message/app/message/presentation/MessageInternalController.java
message/src/main/java/com/faster/message/app/message/presentation/dto/response/PGetAllMessageResponseDto.java

- 이슈 번호: #206 
- **to-be**(변경 후 설명을 여기에 작성) 

[message] 메시지 검색 구현

---

hub/src/main/java/com/faster/hub/app/global/config/RedisCacheConfig.java
hub/src/main/java/com/faster/hub/app/global/config/RedisConfig.java
hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
hub/src/main/resources/properties/redis.yml

[hub] redis config password

---

delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/DeliveryManagerUpdateDto.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/entity/DeliveryManager.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/api/DeliveryManagerUpdateRequestDto.java
delivery/src/main/java/com/faster/delivery/app/global/exception/DeliveryManagerErrorCode.java

[hub] 추가/수정 시, 소속 허브 ID가 존재하는 허브인지 확인

---

delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/CompanyDto.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/strategy/SearchByCompany.java
delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/company/CompanyGetResponseDto.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
delivery/src/main/resources/application-develop.yml
delivery/src/test/delivery-manager.http
delivery/src/test/delivery.http
order/build.gradle

[develop, developManager] 2차 테스트 수정분 반영, zipkin 추가

---

delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/SendMessageApplicationRequestDto.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/SendMessageFeignRequestDto.java
delivery/src/test/delivery.http
message/src/main/java/com/faster/message/app/message/application/dto/request/ASaveMessageRequestDto.java
message/src/main/java/com/faster/message/app/message/application/usecase/MessageServiceImpl.java
message/src/main/java/com/faster/message/app/message/presentation/MessageInternalController.java
message/src/main/java/com/faster/message/app/message/presentation/dto/request/PSaveMessageRequestDto.java
user/src/main/resources/application.yml
user/src/main/resources/properties/jpa.yml
user/src/main/resources/properties/redis.yml

[dlievery, message, user] openfeign 연동 코드 수정 

---

hub/build.gradle
hub/src/main/java/com/faster/hub/app/global/filter/LoggingFilter.java
hub/src/main/resources/application.yml
hub/src/main/resources/logback-spring.xml
hub/src/main/resources/logback/error-file-appender.xml
hub/src/main/resources/logback/info-file-appender.xml
hub/src/main/resources/properties/base.yml
hub/src/main/resources/properties/cloud.yml
hub/src/main/resources/properties/datasource.yml
hub/src/main/resources/properties/zipkin.yml

[hub] zipkin, logback, filter 리펙토링

---

order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
product/src/test/java/com/faster/product/app/product/application/usecase/ProductServiceTest.java

- 이슈 번호: #234
- **as-is**
- (변경 전 설명을 여기에 작성)

[order, product] 오류 보완

---

delivery/build.gradle
delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/repository/DeliveryManagerRepository.java
delivery/src/main/java/com/faster/delivery/app/global/config/RedisConfig.java
delivery/src/main/resources/application-develop.yml
delivery/src/main/resources/application-test.yml
delivery/src/test/java/com/faster/delivery/app/config/EmbeddedRedisConfig.java
delivery/src/test/java/com/faster/delivery/app/config/TearDownExecutor.java
delivery/src/test/java/com/faster/delivery/app/deliverymanager/application/facade/DeliveryManagerFacadeTest.java

[deliverymanager] 배정담당자 등록 시, 시퀀스 동시성 테스트

---

procedure/procedure hub_manager.sql
procedure/procedure_company_product.sql
procedure/procedure_delivery_manager.sql
procedure/procedure_one.sql
procedure/procedure_order.sql

- 이슈 번호: #228 
- **as-is**
```
call generate_company_product_data(100, 100, 100);
call generate_order_data();
call generate_hub_manager_data();
call generate_delivery_managers();
```

[common] 데이터 생성 프로시저 추가

---

.gitignore
delivery/src/main/resources/logback-spring.xml
delivery/src/main/resources/logback/error-file-appender.xml
delivery/src/main/resources/logback/info-file-appender.xml
gateway/src/main/resources/logback-spring.xml
gateway/src/main/resources/logback/error-file-appender.xml
gateway/src/main/resources/logback/info-file-appender.xml
message/src/main/resources/logback-spring.xml
message/src/main/resources/logback/error-file-appender.xml
message/src/main/resources/logback/info-file-appender.xml
server/src/main/resources/logback-spring.xml
server/src/main/resources/logback/error-file-appender.xml
server/src/main/resources/logback/info-file-appender.xml
user/src/main/resources/logback-spring.xml
user/src/main/resources/logback/error-file-appender.xml
user/src/main/resources/logback/info-file-appender.xml

[#241][all] feat: 로그백 추가

---

.gitignore
company/src/main/java/com/faster/company/app/company/domain/entity/Company.java
order/src/main/java/com/faster/order/app/order/domain/entity/OrderItem.java
product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepositoryCustomImpl.java

[order, company, product] 컬럼 길이 수정 및 로직 보완

---

delivery/src/main/java/com/faster/delivery/app/delivery/application/DeliveryScheduler.java
delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
hub/src/main/resources/application.yml
hub/src/main/resources/properties/base.yml
hub/src/main/resources/properties/cloud.yml
hub/src/main/resources/properties/datasource.yml
hub/src/main/resources/properties/jpa.yml
hub/src/main/resources/properties/zipkin.yml

[hub, delivery] 리펙토링

---

Dockerfile.server
docker-compose.yml
gateway/src/main/resources/application-develop.yml
hub/src/main/resources/application-develop.yml
hub/src/main/resources/application.yml
hub/src/main/resources/properties/base.yml
hub/src/main/resources/properties/cloud.yml
hub/src/main/resources/properties/datasource.yml
hub/src/main/resources/properties/jpa.yml
hub/src/main/resources/properties/redis.yml
hub/src/main/resources/properties/zipkin.yml
message/src/main/resources/application-develop.yml
order/src/main/resources/application-develop.yml
product/src/main/resources/application-develop.yml
user/src/main/resources/application-develop.yml
user/src/main/resources/application.yml
user/src/main/resources/properties/redis.yml

[common] 도커 설정 파일 

---

delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/jpa/DeliveryRepositoryCustomImpl.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/repository/DeliveryManagerRepository.java
delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/jpa/DeliveryManagerJpaRepository.java

- 이슈 번호: #251
- **as-is**
- 허브 배송 담당자의 요구사항에대한 이해가 잘 못 된 부분에 대해 로직 수정이 필요
- **to-be**

[delivery] 허브 배송 담당자 로직 수정
